name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check code formatting
      run: |
        if [ -f package.json ] && grep -q '"prettier"' package.json; then
          npm run format:check
        else
          echo "No prettier configuration found, skipping format check"
        fi
        
    - name: Run linting
      run: |
        if [ -f package.json ] && grep -q '"lint"' package.json; then
          npm run lint
        else
          echo "No lint script found, skipping linting"
        fi
        
    - name: Run tests
      run: |
        if [ -f package.json ] && grep -q '"test"' package.json; then
          npm test
        else
          echo "No test script found, skipping tests"
        fi
        
    - name: Build check
      run: |
        if [ -f package.json ] && grep -q '"build"' package.json; then
          npm run build
        else
          echo "No build script found, skipping build check"
        fi
